[package]
name = "my_wl_app"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.160"
memmap2 = "0.9.5"
nix = {version="0.29.0",features = ["fs"]}
rand = "0.8.5"
smithay-client-toolkit = "0.19.2"
