[package]
name = "my_wl_app"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.4"
smithay-client-toolkit = "0.19.2"
xdg = "2.5.2"
water-bg-config = { path = "./config" }
fast_image_resize = {version="5.0.0",features=["image"]}
